<section class="product-hero compact-product-hero"><div><p class="eyebrow">Challenge Owner</p><h1>Manage your Challenge.</h1><p><?= fc_e((string)$challenge['display_name']) ?> · <?= fc_e((string)$challenge['crew_name']) ?></p></div></section>
<div class="section-bar family-section-bar"><a href="/challenge.php?show=history" class="button button-secondary button-small">All Challenges &amp; history</a><span class="status-chip status-chip-neutral"><?= fc_e(fc_challenge_management_label($management)) ?></span></div>
<section class="product-card family-section"><h2>Edit Challenge name</h2><form method="post" action="/challenge-manage.php" class="product-form"><?= fc_csrf_input() ?><input type="hidden" name="action" value="rename"><input type="hidden" name="challenge_public_id" value="<?= fc_e($publicId) ?>"><input type="hidden" name="management_revision" value="<?= fc_e((string)$management['revision']) ?>"><label>Challenge name<input name="display_name" maxlength="140" required value="<?= fc_e((string)$challenge['display_name']) ?>"></label><button type="submit" class="button button-primary">Save name</button></form></section>
<section class="product-card family-section"><p class="card-kicker">Supported Rule changes</p><h2>Change the plan, keep the history.</h2><p>Dates, check-in day, timezone and supported standings settings use the Rules editor. Published versions remain intact. Changing Rules does not accept them for another participant.</p><form method="post" action="/rules.php"><?= fc_csrf_input() ?><input type="hidden" name="action" value="open_challenge_rules"><input type="hidden" name="challenge_public_id" value="<?= fc_e($publicId) ?>"><button class="button button-secondary" type="submit">Open Challenge Rules</button></form></section>
<?php
$actions=[
    'end'=>['title'=>'End Challenge','question'=>'End this Challenge now?','copy'=>'FitCrew will record that you ended this Challenge now. Participation and history stay intact. This action does not create final scores or choose a winner.','button'=>'End Challenge now','danger'=>true],
    'archive'=>['title'=>'Archive Challenge','question'=>'Move this Challenge to the archive?','copy'=>'This hides the Challenge from normal active lists. It does not end the Challenge or erase participation, Rules or results. You can bring it out of the archive later.','button'=>'Archive Challenge','danger'=>false],
    'unarchive'=>['title'=>'Unarchive Challenge','question'=>'Bring this Challenge out of the archive?','copy'=>'Only its archive setting will change. An earlier end or deletion record is not undone.','button'=>'Unarchive Challenge','danger'=>false],
    'delete'=>['title'=>'Delete Challenge','question'=>'Delete this Challenge?','copy'=>'Remove this Challenge from active lists. Rules, participation and required history are kept, and participants keep access to their personal choices. This does not delete accounts, erase health data or disconnect a health provider.','button'=>'Delete Challenge','danger'=>true],
];
?>
<section class="product-card family-section"><h2>Owner controls</h2><p>These controls remain available as the Challenge progresses. They do not override individual acceptance or privacy.</p><div class="family-control-grid">
<?php foreach ($actions as $action=>$spec): ?>
<?php if (($action==='end' && $management['effective_end_at']!==null)||($action==='archive' && $management['archived_at']!==null)||($action==='unarchive' && $management['archived_at']===null)||($action==='delete' && $management['deleted_at']!==null)) continue; ?>
<button class="button <?= $spec['danger'] ? 'button-danger-ghost' : 'button-secondary' ?>" type="button" data-modal-open="manage-<?= fc_e($action) ?>-modal"><?= fc_e($spec['title']) ?></button>
<?php endforeach; ?>
</div><?php if ($management['effective_end_at']!==null): ?><p class="form-help">Effective end: <?= fc_e((string)$management['effective_end_at']) ?> UTC. Final competitive result: not determined by this action.</p><?php endif; ?></section>
<?php foreach ($actions as $action=>$spec): ?>
<dialog class="fc-modal<?= $spec['danger'] ? ' fc-modal-danger' : '' ?>" id="manage-<?= fc_e($action) ?>-modal" data-fitcrew-modal aria-labelledby="manage-<?= fc_e($action) ?>-title"><div class="fc-modal-panel"><header class="fc-modal-hero<?= $spec['danger'] ? ' fc-modal-hero-danger' : '' ?>"><div><p class="eyebrow"><?= fc_e($spec['title']) ?></p><h2 id="manage-<?= fc_e($action) ?>-title"><?= fc_e($spec['question']) ?></h2><p><?= fc_e((string)$challenge['display_name']) ?></p></div><button class="fc-modal-close" type="button" data-modal-close aria-label="Close confirmation">×</button></header><div class="fc-modal-body"><p><?= fc_e($spec['copy']) ?></p><form method="post" action="/challenge-manage.php" class="product-form"><?= fc_csrf_input() ?><input type="hidden" name="action" value="<?= fc_e($action) ?>"><input type="hidden" name="confirm_action" value="<?= fc_e($action) ?>"><input type="hidden" name="challenge_public_id" value="<?= fc_e($publicId) ?>"><input type="hidden" name="management_revision" value="<?= fc_e((string)$management['revision']) ?>"><?php if ($action==='end'): ?><label>Reason <span>Optional</span><textarea name="reason" maxlength="500" rows="3"></textarea></label><?php endif; ?><div class="fc-modal-actions"><button class="button button-secondary" type="button" data-modal-close>Cancel</button><button class="button <?= $spec['danger'] ? 'button-danger' : 'button-primary' ?>" type="submit"><?= fc_e($spec['button']) ?></button></div></form></div></div></dialog>
<?php endforeach; ?>
<?php if ($ownerHistory!==[]): ?><section class="product-card family-section"><p class="card-kicker">Owner action history</p><h2>What changed</h2><ul class="family-history-list"><?php foreach ($ownerHistory as $event): ?><li><strong><?= fc_e(ucwords(strtolower(str_replace('_',' ',(string)$event['event_code'])))) ?></strong><span><?= fc_e((string)$event['actor_name']) ?> · <?= fc_e((string)$event['occurred_at']) ?> UTC</span></li><?php endforeach; ?></ul><p class="form-help">Individual privacy choices and private health data are not shown in this Owner history.</p></section><?php endif; ?>
