<?php if ($challenge !== null): ?>
    <?php require fc_path('views/app/challenge/subnav.php'); ?>
<?php endif; ?>

<section class="product-hero compact-product-hero">
    <div>
        <p class="eyebrow fc-type-meta">People</p>
        <h1 class="fc-type-page-title"><?= fc_e((string) $crew['display_name']) ?></h1>
        <p class="fc-type-body"><?php if ($challenge !== null): ?>Crew relationship and <?= fc_e((string) $challenge['display_name']) ?> participation are shown together without collapsing their separate history.<?php else: ?>Crew membership persists across Challenges. Challenge participation begins only after personal acceptance.<?php endif; ?></p>
    </div>
    <span class="status-chip status-chip-blue"><?= fc_e((string) $activeCrewMemberCount) ?> active Crew <?= $activeCrewMemberCount === 1 ? 'member' : 'members' ?></span>
</section>

<div class="people-summary-grid" aria-label="People summary">
    <article class="people-summary-card"><span>Crew</span><strong><?= fc_e((string) $activeCrewMemberCount) ?> active</strong><p class="fc-type-supporting">Crew membership is the durable relationship.</p></article>
    <article class="people-summary-card"><span><?= $challenge !== null ? 'Current Challenge' : 'Challenge' ?></span><?php if ($challenge !== null): ?><strong><?= fc_e((string) $activeParticipantCount) ?> participating</strong><p class="fc-type-supporting"><?= fc_e((string) $challenge['display_name']) ?> participation is explicit and Challenge-specific.</p><?php else: ?><strong>No current Challenge</strong><p class="fc-type-supporting">Create the next Challenge before inviting people to participate.</p><?php endif; ?></article>
</div>

<div class="people-toolbar" aria-label="People actions">
    <?php if ($challenge !== null): ?><a class="button button-secondary" href="/participation.php?challenge=<?= fc_e(rawurlencode((string) $challenge['public_id'])) ?>">My participation &amp; privacy</a><?php endif; ?>
    <span class="people-toolbar-spacer" aria-hidden="true"></span>
    <?php if ($isOwner && $challenge !== null && $isCurrentChallenge): ?>
        <?php if ($inviteableMembers !== []): ?><button class="button button-secondary" type="button" data-modal-open="invite-existing-member-modal">Invite Crew Member</button><?php endif; ?>
        <button class="button button-primary" type="button" data-modal-open="invite-new-person-modal">Invite Someone New</button>
    <?php endif; ?>
</div>

<section class="section-bar section-bar-spaced"><div><p class="card-kicker fc-type-meta">Crew + Challenge state</p><h2 class="fc-type-section-title">People</h2></div></section>
<div class="people-list">
<?php foreach ($memberships as $member): ?>
    <?php
    $userPublicId = (string) $member['user_public_id'];
    $memberParticipation = $participantByUser[$userPublicId] ?? null;
    $membershipActive = (string) $member['membership_status'] === 'ACTIVE';
    $isCrewOwnerRow = (string) $member['role_code'] === 'OWNER';
    $challengeStatus = $memberParticipation !== null ? (string) $memberParticipation['participation_status'] : null;
    $participantActive = $challengeStatus === 'ACTIVE';
    $canRemoveCrewMember = $isOwner && !$isCrewOwnerRow && $membershipActive;
    $canRemoveParticipant = $isOwner && $challenge !== null && $participantActive && !$isCrewOwnerRow;
    $contactEmail = $participantContactEmails[$userPublicId] ?? ((int) $member['user_id'] === $userId ? fc_current_account_email($pdo) : null);
    $crewLabel = $isCrewOwnerRow ? 'Crew Owner' : ($membershipActive ? 'Crew Member' : 'Removed / Historical');
    $challengeLabel = $challenge === null ? 'No current Challenge' : ($challengeStatus === 'ACTIVE' ? 'Participating' : ($challengeStatus === 'WITHDRAWN' ? 'Withdrawn' : ($challengeStatus === 'REMOVED' ? 'Removed from Challenge' : ($membershipActive ? 'Not Yet Joined Current Challenge' : 'Historical'))));
    ?>
    <article class="people-row<?= !$membershipActive ? ' is-historical' : '' ?>">
        <div class="avatar-badge" aria-hidden="true"><?= fc_e(strtoupper(substr(trim((string) ($member['display_name'] ?: 'F')), 0, 1))) ?></div>
        <div class="people-identity"><strong><?= fc_e((string) ($member['display_name'] ?: 'FitCrew User')) ?></strong><?php if ($contactEmail !== null): ?><span class="people-email"><?= fc_e((string) $contactEmail) ?></span><?php endif; ?><span class="people-state-copy"><?= fc_e($crewLabel) ?><?php if ($challenge !== null): ?> · <?= fc_e((string) $challenge['display_name']) ?>: <?= fc_e($challengeLabel) ?><?php endif; ?></span></div>
        <div class="people-state-chips" aria-label="Person status"><span class="status-chip <?= $membershipActive ? 'status-chip-blue' : 'status-chip-neutral' ?>"><?= fc_e($crewLabel) ?></span><?php if ($challenge !== null): ?><span class="status-chip <?= $participantActive ? 'status-chip-success' : 'status-chip-neutral' ?>"><?= fc_e($challengeLabel) ?></span><?php endif; ?></div>
        <?php if ($canRemoveParticipant || $canRemoveCrewMember): ?><div class="people-actions"><?php if ($canRemoveParticipant): ?><button class="button button-secondary button-small" type="button" data-modal-open="remove-participant-<?= fc_e($userPublicId) ?>">Remove from Challenge</button><?php endif; ?><?php if ($canRemoveCrewMember): ?><button class="button button-danger button-small" type="button" data-modal-open="remove-member-<?= fc_e($userPublicId) ?>">Remove from Crew</button><?php endif; ?></div><?php endif; ?>
    </article>

    <?php if ($canRemoveParticipant): ?><dialog class="fc-modal fc-modal-danger" id="remove-participant-<?= fc_e($userPublicId) ?>" data-fitcrew-modal aria-labelledby="remove-participant-title-<?= fc_e($userPublicId) ?>"><div class="fc-modal-panel"><header class="fc-modal-hero fc-modal-hero-danger"><div><p class="eyebrow">Remove from Challenge</p><h2 id="remove-participant-title-<?= fc_e($userPublicId) ?>">End <?= fc_e((string) ($member['display_name'] ?: 'this participant')) ?>’s Challenge participation?</h2><p>Crew membership remains active. Earlier Challenge participation stays in history.</p></div><button class="fc-modal-close" type="button" data-modal-close aria-label="Close Challenge removal">×</button></header><div class="fc-modal-body"><form method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="action" value="remove_participant"><input type="hidden" name="confirm_action" value="remove_participant"><input type="hidden" name="crew_public_id" value="<?= fc_e((string) $crew['public_id']) ?>"><input type="hidden" name="challenge_public_id" value="<?= fc_e((string) $challenge['public_id']) ?>"><input type="hidden" name="member_public_id" value="<?= fc_e($userPublicId) ?>"><div class="fc-modal-actions"><button class="button button-secondary" type="button" data-modal-close>Keep Participating</button><button class="button button-danger" type="submit">Remove from Challenge</button></div></form></div></div></dialog><?php endif; ?>
    <?php if ($canRemoveCrewMember): ?><dialog class="fc-modal fc-modal-danger" id="remove-member-<?= fc_e($userPublicId) ?>" data-fitcrew-modal aria-labelledby="remove-member-title-<?= fc_e($userPublicId) ?>"><div class="fc-modal-panel"><header class="fc-modal-hero fc-modal-hero-danger"><div><p class="eyebrow">Remove Crew Member</p><h2 id="remove-member-title-<?= fc_e($userPublicId) ?>">Remove <?= fc_e((string) ($member['display_name'] ?: 'this member')) ?> from <?= fc_e((string) $crew['display_name']) ?>?</h2><p>This ends active Crew membership and current Challenge access for this Crew. Historical truth is preserved.</p></div><button class="fc-modal-close" type="button" data-modal-close aria-label="Close Crew member removal">×</button></header><div class="fc-modal-body"><form method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="action" value="remove_crew_member"><input type="hidden" name="confirm_action" value="remove_crew_member"><input type="hidden" name="crew_public_id" value="<?= fc_e((string) $crew['public_id']) ?>"><?php if ($challenge !== null): ?><input type="hidden" name="challenge_public_id" value="<?= fc_e((string) $challenge['public_id']) ?>"><?php endif; ?><input type="hidden" name="member_public_id" value="<?= fc_e($userPublicId) ?>"><div class="fc-modal-actions"><button class="button button-secondary" type="button" data-modal-close>Keep Crew Member</button><button class="button button-danger" type="submit">Remove from Crew</button></div></form></div></div></dialog><?php endif; ?>
<?php endforeach; ?>
</div>

<?php if ($isOwner && $pendingOffers !== []): ?><section class="product-card family-section"><p class="card-kicker fc-type-meta">Existing Crew members</p><h2 class="fc-type-section-title">Challenge Invitation Pending · <?= fc_e((string) count($pendingOffers)) ?></h2><?php foreach ($pendingOffers as $pending): ?><div class="people-pending-row"><div class="people-pending-copy"><strong><?= fc_e((string) ($pending['display_name'] ?: 'FitCrew User')) ?></strong><span>Challenge Invitation Pending · personal acceptance required</span></div><form method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="action" value="cancel_invite"><input type="hidden" name="crew_public_id" value="<?= fc_e((string) $crew['public_id']) ?>"><input type="hidden" name="challenge_public_id" value="<?= fc_e((string) $challenge['public_id']) ?>"><input type="hidden" name="offer_public_id" value="<?= fc_e((string) $pending['public_id']) ?>"><button class="button button-secondary button-small" type="submit">Cancel Invitation</button></form></div><?php endforeach; ?></section><?php endif; ?>

<?php if ($isOwner && $pendingInvitations !== []): ?><section class="product-card family-section"><p class="card-kicker fc-type-meta">New people</p><h2 class="fc-type-section-title">Pending email invitations · <?= fc_e((string) count($pendingInvitations)) ?></h2><div class="people-pending-list"><?php foreach ($pendingInvitations as $invitation): ?><?php $transportStatus=(string)($invitation['transport_status']??'PENDING_SEND');$transportLabel=match($transportStatus){'TRANSPORT_ACCEPTED'=>'Email accepted by transport','TRANSPORT_FAILED'=>'Email send failed',default=>'Email pending send'}; ?><div class="people-pending-row"><div class="people-pending-copy"><strong><?= fc_e((string) $invitation['invited_email']) ?></strong><?php if ($invitation['challenge_id'] === null): ?><span>Legacy Crew-only invitation · <?= fc_e($transportLabel) ?></span><small>This invitation cannot accept the current Challenge. Cancel it and send a new Challenge invitation.</small><?php else: ?><span><?= fc_e((string) $invitation['challenge_name']) ?> · Challenge Invitation Pending · <?= fc_e($transportLabel) ?></span><?php endif; ?></div><div class="people-actions"><?php if ($invitation['challenge_id'] !== null): ?><form method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="action" value="resend_invitation"><input type="hidden" name="crew_public_id" value="<?= fc_e((string) $crew['public_id']) ?>"><?php if ($challenge !== null): ?><input type="hidden" name="challenge_public_id" value="<?= fc_e((string) $challenge['public_id']) ?>"><?php endif; ?><input type="hidden" name="invitation_public_id" value="<?= fc_e((string) $invitation['public_id']) ?>"><button class="button button-secondary button-small" type="submit">Resend</button></form><?php endif; ?><form method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="action" value="cancel_invitation"><input type="hidden" name="crew_public_id" value="<?= fc_e((string) $crew['public_id']) ?>"><?php if ($challenge !== null): ?><input type="hidden" name="challenge_public_id" value="<?= fc_e((string) $challenge['public_id']) ?>"><?php endif; ?><input type="hidden" name="invitation_public_id" value="<?= fc_e((string) $invitation['public_id']) ?>"><button class="button button-danger button-small" type="submit">Cancel</button></form></div></div><?php endforeach; ?></div></section><?php endif; ?>

<?php if ($isOwner && $challenge !== null && $isCurrentChallenge): ?>
<dialog class="fc-modal" id="invite-new-person-modal" data-fitcrew-modal aria-labelledby="invite-new-person-title"><div class="fc-modal-panel"><header class="fc-modal-hero"><div><p class="eyebrow">Invite Someone New</p><h2 id="invite-new-person-title">Invite to <?= fc_e((string) $challenge['display_name']) ?>.</h2><p>One email invitation lets the recipient review the Challenge, authenticate, and explicitly accept.</p></div><button class="fc-modal-close" type="button" data-modal-close aria-label="Close invitation">×</button></header><div class="fc-modal-body"><form class="product-form" method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="action" value="invite_member"><input type="hidden" name="crew_public_id" value="<?= fc_e((string) $crew['public_id']) ?>"><input type="hidden" name="challenge_public_id" value="<?= fc_e((string) $challenge['public_id']) ?>"><label>Email address<input type="email" name="email" maxlength="254" required autocomplete="email" placeholder="family@example.com"></label><p class="form-help">The invitation itself verifies access to this email. Health connection comes later.</p><div class="fc-modal-actions"><button class="button button-secondary" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Send Challenge Invitation</button></div></form></div></div></dialog>
<?php if ($inviteableMembers !== []): ?><dialog class="fc-modal" id="invite-existing-member-modal" data-fitcrew-modal aria-labelledby="invite-existing-member-title"><div class="fc-modal-panel"><header class="fc-modal-hero"><div><p class="eyebrow">Invite Crew Member</p><h2 id="invite-existing-member-title">Invite an existing Crew member.</h2><p>Crew membership stays intact. Challenge participation begins only after that person accepts.</p></div><button class="fc-modal-close" type="button" data-modal-close aria-label="Close Crew member invitation">×</button></header><div class="fc-modal-body"><form class="product-form" method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="action" value="invite"><input type="hidden" name="crew_public_id" value="<?= fc_e((string) $crew['public_id']) ?>"><input type="hidden" name="challenge_public_id" value="<?= fc_e((string) $challenge['public_id']) ?>"><label>Crew member<select name="member_public_id" required><option value="">Choose a Crew member</option><?php foreach ($inviteableMembers as $member): ?><option value="<?= fc_e((string) $member['user_public_id']) ?>"><?= fc_e((string) ($member['display_name'] ?: 'FitCrew User')) ?></option><?php endforeach; ?></select></label><p class="form-help">This records a Challenge invitation for someone already in the Crew. It does not create participation.</p><div class="fc-modal-actions"><button class="button button-secondary" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Invite to Challenge</button></div></form></div></div></dialog><?php endif; ?>
<?php endif; ?>
