<?php require fc_path('views/app/challenge/subnav.php'); ?>
<section class="product-hero compact-product-hero"><div><p class="eyebrow">Participants</p><h1><?= fc_e((string)$challenge['display_name']) ?></h1><p>Invite people at any stage. Each person accepts for themselves.</p></div><span class="status-chip status-chip-blue"><?= fc_e((string)count(array_filter($participants,static fn(array $p):bool=>$p['participation_status']==='ACTIVE'))) ?> active</span></section>
<section class="section-bar family-section-bar"><a class="button button-secondary" href="/participation.php?challenge=<?= fc_e(rawurlencode((string)$challenge['public_id'])) ?>">My participation &amp; privacy</a><?php if ($isOwner): ?><button class="button button-primary" type="button" data-modal-open="invite-participant-modal">Invite participant</button><?php endif; ?></section>
<?php if ($participants===[]): ?><div class="inline-empty-state"><strong>No roster to display.</strong><span>Pending invitations do not count as active participation. Former participants can use My participation &amp; privacy for their personal record.</span></div><?php else: ?>
<div class="participant-list"><?php foreach ($participants as $participant): ?>
<article class="participant-row<?= $participant['participation_status']!=='ACTIVE' ? ' is-muted' : '' ?>"><div class="avatar-badge" aria-hidden="true"><?= fc_e(strtoupper(substr((string)($participant['display_name'] ?: 'F'),0,1))) ?></div><div class="participant-main"><strong><?= fc_e((string)($participant['display_name'] ?: 'FitCrew member')) ?></strong><span><?= $participant['entry_kind']==='LATE' ? 'Joined after the planned start · eligibility not determined here' : 'Participation recorded · eligibility determined separately' ?></span></div><span class="status-chip status-chip-neutral"><?= fc_e(ucfirst(strtolower((string)$participant['participation_status']))) ?></span><?php if ($isOwner && $participant['participation_status']==='ACTIVE'): ?><button class="member-remove-button" type="button" data-modal-open="remove-participant-<?= fc_e((string)$participant['user_public_id']) ?>">Remove</button><?php endif; ?></article>
<?php if ($isOwner && $participant['participation_status']==='ACTIVE'): ?><dialog class="fc-modal fc-modal-danger" id="remove-participant-<?= fc_e((string)$participant['user_public_id']) ?>" data-fitcrew-modal aria-labelledby="remove-participant-title-<?= fc_e((string)$participant['user_public_id']) ?>"><div class="fc-modal-panel"><header class="fc-modal-hero fc-modal-hero-danger"><div><p class="eyebrow">Remove participant</p><h2 id="remove-participant-title-<?= fc_e((string)$participant['user_public_id']) ?>">Remove <?= fc_e((string)($participant['display_name'] ?: 'this participant')) ?>?</h2></div><button class="fc-modal-close" type="button" data-modal-close aria-label="Close participant removal">×</button></header><div class="fc-modal-body"><p>Their active participation ends now. Earlier participation and required results remain in history. This does not remove Crew membership or change their personal privacy settings.</p><form method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="challenge_public_id" value="<?= fc_e((string)$challenge['public_id']) ?>"><input type="hidden" name="member_public_id" value="<?= fc_e((string)$participant['user_public_id']) ?>"><input type="hidden" name="action" value="remove"><input type="hidden" name="confirm_action" value="remove"><div class="fc-modal-actions"><button class="button button-secondary" type="button" data-modal-close>Keep participant</button><button class="button button-danger" type="submit">Remove participant</button></div></form></div></div></dialog><?php endif; ?>
<?php endforeach; ?></div><?php endif; ?>
<?php if ($isOwner): ?>
<section class="product-card family-section"><p class="card-kicker">Separate from members and active participants</p><h2>Pending participant invitations · <?= fc_e((string)count($pendingOffers)) ?></h2><?php if ($pendingOffers===[]): ?><p>No pending participant invitations.</p><?php endif; ?><?php foreach ($pendingOffers as $pending): ?><div class="family-pending-row"><div><strong><?= fc_e((string)($pending['display_name'] ?: 'FitCrew member')) ?></strong><span>Pending personal acceptance</span></div><form method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="challenge_public_id" value="<?= fc_e((string)$challenge['public_id']) ?>"><input type="hidden" name="offer_public_id" value="<?= fc_e((string)$pending['public_id']) ?>"><input type="hidden" name="action" value="cancel_invite"><button class="button button-secondary button-small" type="submit">Cancel invitation</button></form></div><?php endforeach; ?></section>
<dialog class="fc-modal" id="invite-participant-modal" data-fitcrew-modal aria-labelledby="invite-participant-title"><div class="fc-modal-panel"><header class="fc-modal-hero"><div><p class="eyebrow">Invite participant</p><h2 id="invite-participant-title">Let them choose to join.</h2><p>Inviting does not accept the contract or privacy choices for another person.</p></div><button class="fc-modal-close" type="button" data-modal-close aria-label="Close participant invitation">×</button></header><div class="fc-modal-body"><?php if ($inviteableMembers===[]): ?><p>There are no additional current Crew members to invite.</p><?php else: ?><form class="product-form" method="post" action="/participants.php"><?= fc_csrf_input() ?><input type="hidden" name="challenge_public_id" value="<?= fc_e((string)$challenge['public_id']) ?>"><input type="hidden" name="action" value="invite"><label>Crew member<select name="member_public_id" required><option value="">Choose a member</option><?php foreach ($inviteableMembers as $member): ?><option value="<?= fc_e((string)$member['user_public_id']) ?>"><?= fc_e((string)($member['display_name'] ?: 'FitCrew member')) ?></option><?php endforeach; ?></select></label><p class="form-help">This is an in-app Challenge invitation for someone already in your Crew. They will see it in their Challenge list. It is not a Crew email invitation and no email is sent by this action.</p><div class="fc-modal-actions"><button class="button button-secondary" type="button" data-modal-close>Cancel</button><button class="button button-primary" type="submit">Invite to Challenge</button></div></form><?php endif; ?></div></div></dialog>
<?php endif; ?>
