CREATE TABLE challenge_rule_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    challenge_id BIGINT UNSIGNED NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    version_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    supersedes_version_id BIGINT UNSIGNED NULL,
    scoring_standard_code VARCHAR(64) NOT NULL DEFAULT 'BODY_COMPOSITION_V1_0',
    planned_start_date DATE NULL,
    duration_days SMALLINT UNSIGNED NOT NULL DEFAULT 56,
    challenge_timezone VARCHAR(64) NOT NULL,
    weekly_checkin_day TINYINT UNSIGNED NOT NULL DEFAULT 0,
    live_leaderboard_visible TINYINT(1) NOT NULL DEFAULT 1,
    created_by_user_id BIGINT UNSIGNED NOT NULL,
    published_by_user_id BIGINT UNSIGNED NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    published_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_challenge_rule_versions_public_id (public_id),
    UNIQUE KEY uq_challenge_rule_versions_number (challenge_id, version_number),
    KEY idx_challenge_rule_versions_current (challenge_id, version_status, version_number),
    KEY idx_challenge_rule_versions_supersedes (supersedes_version_id),
    CONSTRAINT fk_challenge_rule_versions_challenge FOREIGN KEY (challenge_id) REFERENCES challenges(id) ON DELETE RESTRICT,
    CONSTRAINT fk_challenge_rule_versions_supersedes FOREIGN KEY (supersedes_version_id) REFERENCES challenge_rule_versions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_challenge_rule_versions_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_challenge_rule_versions_publisher FOREIGN KEY (published_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_challenge_rule_versions_status CHECK (version_status IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT chk_challenge_rule_versions_duration CHECK (duration_days BETWEEN 7 AND 365),
    CONSTRAINT chk_challenge_rule_versions_checkin_day CHECK (weekly_checkin_day BETWEEN 0 AND 6),
    CONSTRAINT chk_challenge_rule_versions_live_visibility CHECK (live_leaderboard_visible IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
